enum ActionTypeKeys {
    GETUXO_INPROGRESS = "GETUXO_INPROGRESS",
    GETUXO_SUCCESS = "GETUXO_SUCCESS",
    GETUXO_FAIL = "GETUXO_FAIL",

    GENERATEUXO_INPROGRESS = "GENERATEUXO_INPROGRESS",
    GENERATEUXO_SUCCESS = "GENERATEUXO_SUCCESS",
    GENERATEUXO_FAIL = "GENERATEUXO_FAIL",

    GETALLUXOS_INPROGRESS = "GETALLUXOS_INPROGRESS",
    GETALLUXOS_SUCCESS = "GETALLUXOS_SUCCESS",
    GETALLUXOS_FAIL = "GETALLUXOS_FAIL"
}

export default ActionTypeKeys;